name: GitGoogleContainer
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Docker pull and push
        run: |
          docker login ghcr.io -u fanggege123 -p "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"
          docker pull k8s.gcr.io/ingress-nginx/controller:v0.35.0  
          docker tag  k8s.gcr.io/ingress-nginx/controller:v0.35.0  ghcr.io/fanggege123/ingress-nginx/controller:v0.35.0       
          docker push ghcr.io/fanggege123/ingress-nginx/controller:v0.35.0
